# Generated by Django 3.0.1 on 2019-12-23 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('mesh_ip', models.IntegerField(default=0)),
                ('mesh', models.IntegerField(default=0)),
                ('gas', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('DA', models.IntegerField(default=0)),
                ('PLX', models.IntegerField(default=0)),
                ('database', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Member Stats',
            },
        ),
    ]
