# Generated by Django 3.0.1 on 2019-12-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'User Stats'},
        ),
    ]
